#!/usr/bin/python3
# Compare all spreadsheets in directory to each other
# Derek Fujimoto
# June 2018

import multifile_comparer
import os, argparse

# run if main
if __name__ == '__main__':
    
    # set up argument parser
    parser = argparse.ArgumentParser(description='Run a pairwise comparison '+\
        'of all spreadsheets on target PATH. Look for pairs with common'+\
        ' features indicative of plagiarism.')

    # directory
    parser.add_argument("PATH",
                        help='evaluate spreadsheets found on PATH',
                        action='store')

    # dry-run don't save spreadsheet
    parser.add_argument("-d", "--dry",
                        help="Dry run, don't write to speadsheet",
                        dest='dry',
                        action='store_true',
                        default=False)

    # explain headers
    parser.add_argument("--explain",
                        help='Print calculation methodology of table values',
                        dest='explain',
                        action='store_true',
                        default=False)

    # log
    parser.add_argument("-l", "--log",
                        help='write print out table to text file',
                        dest='logfile',
                        action='store',
                        default='')
    
    # options
    opt_help="comma-separated list of items to compare "+\
             "(default: 'meta,exact,string,geo')"
                    
    parser.add_argument("-o", "--options",
                        help=opt_help,
                        dest='options',
                        action='store',
                        default='meta,exact,string,geo')
    
    # print lines
    parser.add_argument("-p", "--print",
                        help='Print full summary of each comparison',
                        dest='print',
                        action='store_true',
                        default=False)
    
    # quiet mode
    parser.add_argument("-q", "--quiet",
                        help='No print output to stdout',
                        dest='quiet',
                        action='store_true',
                        default=False)
    
    # save as spreadsheet
    parser.add_argument("-s", "--save",
                        help='write printout to xlsx file',
                        dest='savefile',
                        action='store',
                        default='')
    
    # parse
    args = parser.parse_args()

    # -----------------------------------------------------------------------
    # Set up and run comparison
    if args.explain:
        print(multifile_comparer.explanation)
    
    else:
        c = multifile_comparer.multifile_comparer(args.PATH)
        c.compare(options=args.options,do_print=args.print)
        
        if not args.quiet:
            c.print_table(filename=args.logfile)
            
        if not args.dry:
            c.print_spreadsheet(filename=args.savefile)
